name = "follow_data_fix"
version = "1.0"
[dbConf]
[dbConf.users_data]
driver = "mysql"
dsn = "root:111111@tcp(127.0.0.1:3306)/luowen?charset=utf8"

[redisConf]
[redisConf.social]
host = "127.0.0.1"
password = ""
port = 6379
db = 0
socket = ""



