name = "follow_data_fix"
version = "1.0"
hotfix = true
hotfixUIDList = "15,250"
[dbConf]
[dbConf.users_data]
driver = "mysql"
dsn = "app_zhanqi:xLgU^8hd@tcp(10.62.62.27:3306)/users_data?charset=utf8"
maxOpenConns = 500
maxIdleConns = 300
[dbConf.contents]
driver = "mysql"
dsn = "app_zhanqi:xLgU^8hd@tcp(10.62.62.27:3306)/contents?charset=utf8"
maxOpenConns = 500
maxIdleConns = 300

[redisConf]
[redisConf.social]
host = "127.0.0.1"
password = ""
port = 6379
db = 0
socket = ""
