name = "follow_data_fix"
version = "1.0"
[dbConf]
[dbConf.users_data]
driver = "mysql"
dsn = "root:111111@tcp(127.0.0.1:3306)/users_data?charset=utf8"
# 最大连接数
maxOpenConns = 500
# 最大空闲连接数
maxIdleConns = 300

[redisConf]
[redisConf.social]
host = "127.0.0.1"
password = ""
port = 8888
db = 0
socket = ""
