name = "datafix script"
version = "1.0"
[dbConf]
[dbConf.users_data]
 host = "10.62.62.114"
 username = "app_zhanqi"
 password = "123456"
 database = "users_data"
 port = 8066

[redisConf]
[redisConf.social]
host = "127.0.0.1"
port = 8888
socket = "/dev/shm/social.socket"
db = 0
password = ""
